---
title: "AfterRevisions_Figure3"
output: html_notebook
---

# Load in libraries
```{r}
suppressWarnings(suppressMessages(library(readr)))
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(vegan)))
suppressWarnings(suppressMessages(library(umap)))
source("Functions.R")
```

# Bring in neighborhood analysis by importing affinity matrixes. Outputs Affinity.long
```{r}
## Bring data in by FOV 
studylist <- c("3402_CECUM", "3402_COLON", "3405_CECUM", "3405_COLON", "3406_CECUM", "3406_COLON", "3407_CECUM", "3407_COLON", "3409_CECUM", "3409_COLON", "3412_CECUM", "3412_COLON", "3413_CECUM", "3413_COLON", "3414_CECUM", "3414_COLON", "3415_CECUM", "3415_COLON", "3422_CECUM", "3422_COLON", "3423_CECUM", "3423_COLON", "3424_CECUM", "3424_COLON", "3428_CECUM", "3428_COLON", "3429_CECUM", "3429_COLON", "3430_CECUM", "3430_COLON", "3434_CECUM", "3434_COLON", "3435_CECUM", "3435_COLON", "3436_CECUM", "3436_COLON", "3438_CECUM", "3438_COLON", "3441_CECUM", "3441_COLON", "3442_CECUM", "3442_COLON", "3446_CECUM", "3446_COLON", "3447_CECUM", "3447_COLON", "3448_CECUM", "3448_COLON", "3451_CECUM", "3451_COLON", "3452_CECUM", "3452_COLON", "3454_CECUM", "3454_COLON" )

df.list <- list()
for (i in 1:length(studylist))  {
  all.files <- list.files(paste0('../data/BugCountsR5_Mar242023/', studylist[i], "/radius_5/"))  
  all.files <- grep("affinity_ratio_matrix_rep", all.files, value = TRUE) 
  file.df <- tibble(filename = all.files)
  file.df.paths <- file.df %>%
    mutate(filepath = paste0('../data/BugCountsR5_Mar242023/', studylist[i], "/radius_5/", filename))
  file.df.paths$study <- studylist[i]
  df.list[[i]] <- file.df.paths # add it to your list
}

df.list.all <- do.call(rbind, df.list)
df.list.all


# for each file, read the csv, and filename as column
raw.data <- lapply(df.list.all$filepath, read.csv.and.add.filename.CB) %>% bind_rows() 

## add in column for mouse, location, tissue_replicate, and FOV
raw.data.wide <- raw.data %>% mutate(Mouse = str_sub(filepath, 37, 40)) %>% mutate(Tissue = str_sub(filepath, 42, 46)) %>%
  mutate(Section = str_sub(filepath, 83, 83)) %>% mutate(FoV = str_sub(filepath, 89, 89))

 
# import tissue metadata
md <- read.csv("../data/Tissues_Metadata.csv")
#shorten metadata to only include samples we sent (3 mice per group)
mouse <- c("3402", "3405", "3406" , "3407", "3409", "3412", "3413", "3414", "3415", "3422", "3423", "3424", "3428", "3429", "3430", "3434", "3435", "3436", "3438", "3441", "3442", "3446", "3447", "3448", "3451", "3452", "3454")

# clean up the metadata to only include rows for the mice we submitted to kanvas
md.images <- md[,1:4] %>% filter (Mouse %in% mouse)
md.images$Mouse <- as.character(md.images$Mouse)

Affinity.wide <- left_join(raw.data.wide, md.images, by = "Mouse")

Affinity.long <- Affinity.wide %>% dplyr::select(-filepath) %>% 
  pivot_longer(cols = 2:64, names_to = "Bug_in_Hood", values_to = "Affinity_Score", names_prefix = "Bug_" )

# Add in Bug names
Affinity.long$Bug_in_Hood <- Affinity.long$Bug_in_Hood %>% as.numeric() %>% round(digits = 0) %>% as.character()
ASV <- read.csv("../data/asv_lineage_abundance.csv")

ASV$ASV_Cluster_ID <- as.character(ASV$ASV_Cluster_ID)
Affinity.long <- left_join(Affinity.long, ASV, by = c("Bug_in_Hood" = "ASV_Cluster_ID"))

Affinity.long$Sample <- paste(Affinity.long$Treatment, Affinity.long$Day, Affinity.long$Tissue, 
                                Affinity.long$Mouse, Affinity.long$Section, Affinity.long$FoV, sep = "_") 
```


# Suplemental Table 2 Neighbourhood changes
```{r}
# mapply with 3 lists, one for BUGID, one for tissue, and one for antibiotics
Bugs <- Affinity.long$Center_Bug %>% unique
Bug.list <- lapply(Bugs, rep, 4) %>% unlist()
Tissue.list <- c("CECUM", "COLON") %>% rep(length(Bugs)*2)
Abx.list <- rep(c(rep("Ampicillin", 2), rep("Vancomycin", 2)), times = length(Bugs))

length(Bugs)
length(Bug.list)
length(Tissue.list)
length(Abx.list)
Affinity.long$Sample <- paste(Affinity.long$Treatment, Affinity.long$Day, Affinity.long$Tissue, 
                                Affinity.long$Mouse, Affinity.long$Section, Affinity.long$FoV, sep = "_") 

ldf <- list(Affinity.long)
#get matrix for each possible scenario
mlist <- mapply(get.matrix.rev, ldf, Bug.list, Tissue.list, Abx.list)
#get rid of empty dfs
mlist <- mlist[sapply(mlist, function(x) dim(x)[1]) > 1]
# get metadata for each scenario
mdlist<- mapply(get.md.rev, ldf, Bug.list, Tissue.list, Abx.list)
#get rid of empty dfs
mdlist <- mdlist[sapply(mdlist, function(x) dim(x)[1]) > 1]

#remove dfs that have only one type of treatment group where you can't do the comparison
mdlistnew <- list()
for (i in 1:length(mdlist)) {
  if (length(unique(mdlist[[i]]$Treatment)) >1) 
    {mdlistnew[[i]] <- mdlist[[i]]}
}
length(mdlistnew)


mlistnew <- list()
for (i in 1:length(mdlist)) {
  if (length(unique(mdlist[[i]]$Treatment)) >1) 
    {mlistnew[[i]] <- mlist[[i]]}
}
length(mlistnew)
mlistnew <- mlistnew[lengths(mlistnew) != 0]
mdlistnew <- mdlistnew[lengths(mdlistnew) != 0]

datalist = list()  

for(i in 1:length(mlistnew)) {
  #get the matrix and metadata for each center bug
  mdlistnew[[i]] <- dplyr::select(mdlistnew[[i]], Sample:Center_Bug) 
  # do adonis on each matrix x metadata
  results <- adonis(mlistnew[[i]] ~ Treatment, mdlistnew[[i]], parallel = 2, na.rm = TRUE) 
  #put the results into a df
  a.df <- results$aov.tab %>% as.data.frame()
  # add a group to know what we're comparing
  Groups <- unique(mdlistnew[[i]]$Treatment) 
  Group <- grep("*in", Groups, value = T)
  a.df$Group <- paste(Group, mdlistnew[[i]]$Tissue, sep = "_") %>% unique()
  # add in the center bug
  a.df$CenterBug <- mdlistnew[[i]]$Center_Bug %>% unique()
  datalist[[i]] <- a.df
}
big_data <- do.call(rbind, datalist)

AdonisResults <- big_data %>% filter(!is.na(`Pr(>F)`)) %>% filter(`Pr(>F)` < 0.1) %>% arrange(-R2)

datalist2 <- list()  

for(i in 1:length(mlistnew)) {
  #get the matrix and metadata for each center bug
  mdlistnew[[i]] <- dplyr::select(mdlistnew[[i]], Sample:Center_Bug) 
  # do adonis on each matrix x metadata
  results <- adonis(mlistnew[[i]] ~ Treatment, mdlistnew[[i]], parallel = 2, na.rm = TRUE) 
  #put the coefficients into a df
  coef <- coefficients(results)["Treatment1",] %>% as.data.frame()
  names(coef) <- "value"
  top.coef <- coef %>% drop_na() %>% arrange(-abs(value)) %>% rownames_to_column("Neighbour_Bug")
  # add a group to know what we're comparing
  Groups <- unique(mdlistnew[[i]]$Treatment) 
  Group <- grep("*in", Groups, value = T)
  top.coef$Group <- paste(Group, mdlistnew[[i]]$Tissue, sep = "_") %>% unique()
    # add in the center bug
  top.coef$CenterBug <- mdlistnew[[i]]$Center_Bug %>% unique()
  datalist2[[i]] <- top.coef[1,]
}

big_data2 <- do.call(rbind, datalist2)


#join together
FullPermanova <- inner_join(AdonisResults, big_data2, by = c("Group", "CenterBug"))
FullPermanova <- FullPermanova %>% dplyr::select(`Pr(>F)`, Group, CenterBug, Neighbour_Bug, value, R2)
#add in name of CenterBug
FullPermanova$CenterBug <- as.character(FullPermanova$CenterBug)
FullPermanova <- FullPermanova %>% left_join(dplyr::select(ASV, ASV_Cluster_ID, ASV_Cluster_Scientific_Name) , by = c("CenterBug" = "ASV_Cluster_ID"))
colnames(FullPermanova)[7] <- "CenterBugName"
colnames(FullPermanova)[1] <- "pValue"
colnames(FullPermanova)[5] <- "coefficient"

FullPermanova <- separate(FullPermanova, Group, into = c("Treatment", "Tissue"), sep = "\\_")
#adjust for multiple comparisons
FullPermanova$p.adj <- p.adjust(FullPermanova$pValue, method = "fdr")
AdjustedPermanova <- FullPermanova %>%filter(p.adj < 0.05)


FullPermanova %>% filter(CenterBug == 30)
AdjustedPermanova %>% arrange(-R2)

#write.csv(FullPermanova, "../Results/SupplementalTable2_PairwisePermanovaResults.csv")
```

# Figure 5A
```{r}
set.seed(27)

BUGID <- 63 #Bug with largest R2

# Filter for your bug
OneBug <- Affinity.long %>% filter(Center_Bug == BUGID)

# sample by feature matrix
OneBug.wide <- OneBug %>% dplyr::select(Affinity_Score, ASV_Cluster_Scientific_Name, Sample) %>% 
  pivot_wider(names_from = ASV_Cluster_Scientific_Name, values_from = Affinity_Score)

# NAs come from not existing in the affinity matrix, so it can be replaced with 0
OneBug.wide[is.na(OneBug.wide)] <- 0

umap.affinity <- umap(column_to_rownames(OneBug.wide, "Sample"), n_neighbors = 10)

# get metadata
labels <- OneBug %>% dplyr::select(ASV_Cluster_Scientific_Name, Sample, Tissue, Treatment, Day, Affinity_Score) %>% 
  pivot_wider(names_from = ASV_Cluster_Scientific_Name, values_from = Affinity_Score) %>% .[,1:4] 
#add row numbers as ID
labels$ID <- 1:dim(labels)[1]


umap_df <- umap.affinity$layout %>%
  as.data.frame()%>%
  rename(UMAP1="V1",
         UMAP2="V2") %>%
  mutate(ID = row_number())%>%
  left_join(labels, by="ID")

# fix treatment names 
umap_df$Treatment <- gsub("H2O", "Water", umap_df$Treatment)
umap_df$Treatment <- as.factor(umap_df$Treatment)
umap_df$Treatment <- factor(umap_df$Treatment, levels = c("Water", "Ampicillin", "Vancomycin"))

colours <- c("#335780", "#7dace3", "#D5490C",
          "#f2ae49",  "#03663F", "#60d681")

umap_df %>% filter(Day == 35) %>% 
  ggplot(aes(x = UMAP1, y = UMAP2, color = interaction(Tissue,Treatment, sep = ":") ))+
  geom_point(size = 2, stroke = 1, aes(shape = Treatment)) +
  facet_wrap(~Tissue) +
  stat_ellipse(type = "t") +
  theme(text = element_text(size = 18)) +
  labs(x = "UMAP1",
       y = "UMAP2",
      title = "B. theta") +
  scale_shape_manual(values= c(1,2,3)) + 
  scale_colour_manual(values=colours) +
  theme_bw(base_size = 14)

#ggsave("../Figures/Spatial/RC_30_UMAP.pdf", width = 8, height = 6)
```

# FIGURE 5B
```{r}
set.seed(27)

BUGID <- 63 #largest R2

# Filter for your bug
OneBug <- Affinity.long %>% filter(Center_Bug == BUGID)

OneBug$Treatment <- gsub("H2O", "Water", OneBug$Treatment)
OneBug$Treatment <- as.factor(OneBug$Treatment)
OneBug$Treatment <- factor(OneBug$Treatment, levels = c("Water", "Ampicillin", "Vancomycin"))

# sample by feature matrix
OneBug.wide <- OneBug %>% dplyr::select(Affinity_Score, ASV_Cluster_Scientific_Name, Sample) %>% 
  pivot_wider(names_from = ASV_Cluster_Scientific_Name, values_from = Affinity_Score)

# NAs come from not existing in the affinity matrix, so it can be replaced with 0
OneBug.wide[is.na(OneBug.wide)] <- 0

# Filter
OneBug.wide.Van.Cecum <- OneBug %>%
  filter(Tissue == "COLON", Day == 35) %>% 
  dplyr::select(ASV_Cluster_Scientific_Name, Sample, Affinity_Score) %>%
  pivot_wider(names_from = ASV_Cluster_Scientific_Name, values_from = Affinity_Score)

# Change NA to 0 (NAs come from not existing in the affinity matrix)
OneBug.wide.Van.Cecum[is.na(OneBug.wide.Van.Cecum)] <- 0
OneBug.wide.Van.Cecum <- OneBug.wide.Van.Cecum %>% column_to_rownames("Sample")

#Make NMDS
NMDS3 <- metaMDS(OneBug.wide.Van.Cecum, k = 2, trymax = 100, trace = F, autotransform = FALSE,
                 distance="bray")

# get sample metadata 
OneBug.wide.Van.Cecum.md <- OneBug %>%
  filter(Tissue == "COLON", Day == 35) %>%
  dplyr::select(ASV_Cluster_Scientific_Name, Sample, Affinity_Score, Treatment, Tissue, Day) %>%
  pivot_wider(names_from = ASV_Cluster_Scientific_Name, values_from = Affinity_Score) %>%
  .[1:4]

biplot.df1 <- scores(NMDS3)$sites %>% as_tibble(rownames = "Sample") %>%
  left_join(OneBug.wide.Van.Cecum.md, by = "Sample" ) %>% dplyr::select(Sample, NMDS1, NMDS2)

biplot.df1$Score <- "Site"
colnames(biplot.df1)[1] <- "Label"

biplot.df2 <- scores(NMDS3)$species %>% as_tibble(rownames = "Label")
biplot.df2$Score <- "Species"
biplot.df <- rbind(biplot.df1, biplot.df2) %>% filter(!is.na(NMDS1))


#filter Bug segments to only include the largest effect
biplot.df3 <- scores(NMDS3)$species %>% as_tibble(rownames = "Label") %>% filter(abs(NMDS1) > 1 | abs(NMDS2) > 1)

biplot.df3$Score <- "Species"
biplot.df4 <- rbind(biplot.df1, biplot.df3) 

colours.colon <- c( "#7dace3", 
          "#f2ae49",   "#60d681")

ggbiplot <- scores(NMDS3)$sites %>% as_tibble(rownames = "Sample") %>%
  left_join(OneBug.wide.Van.Cecum.md, by = "Sample" ) %>%
  ggplot(aes(NMDS1, NMDS2, colour = Treatment)) +
  geom_point(size =3, stroke = 1.5, aes(shape = Treatment)) + #biplot.df will give all the segments
  scale_colour_manual(values=colours.colon) +
  scale_shape_manual(values=c(1,2,3)) +
  geom_segment(data = filter(biplot.df4, Score == "Species"), 
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2), inherit.aes = FALSE, size = 0.2) +
  ggtitle(paste0(BUGID," B. thetaiotaomicron neighborhood in the colon"))


biplot.df4$Label[29:36] <- c(
"C. scindens ",
"K. alysoides"    ,                  
"D. freteri 2"   ,                                                                      
 "B. thetaiotaomicron" ,                                                                
"D. dubosii 4"      ,                                                                   
"M. formatexigens  1" ,                                                              
"B. uniformis"     ,                                                                    
 "E. massiliensis 2"  
)
library(ggrepel)
ggbiplot + geom_text_repel(data = filter(biplot.df4, Score == "Species"),  aes(x = NMDS1, y = NMDS2, label = Label), inherit.aes = FALSE, size = 3) + theme_bw(base_size = 14) 
#ggsave("../Figures/Figure 5b Btheta.pdf", width =7, height = 6)
```

# Figure 5c Coefficient plots
```{r}
# Coefficients plots
day <- 35
OneBug.wide.md <- OneBug %>%
  dplyr::select(Affinity_Score, ASV_Cluster_Scientific_Name, Sample, Tissue, Day, Treatment) %>%
  pivot_wider(names_from = ASV_Cluster_Scientific_Name, values_from = Affinity_Score) %>% filter(Day == day)

# make matrix match md
tokeep <- OneBug.wide.md$Sample
OneBug.wide.filt <- OneBug.wide %>%
  rownames_to_column("Sample") %>%
  filter(Sample %in% tokeep) %>%
  column_to_rownames("Sample")

adonis.143 <- adonis(select_if(OneBug.wide.filt, is.numeric) ~ Tissue*Treatment, 
                     data = OneBug.wide.md, parallel = 2)
coef <- coefficients(adonis.143)["Tissue1",]
top.coef <- coef[rev(order(abs(coef)))[1:10]]
# shorten names for plot
top.coef2 <- top.coef %>% as.data.frame() %>% rownames_to_column("Taxa")
top.coef2
top.coef2$Taxa <- c(
"D. dubosii 4"	,
"C. scindens" ,
"P. capillosus | F. plautii" ,
"L. phytofermentans" ,
"E. oxidoreducens 1"	,
"R. peoriensis" ,
"A. rubiinfantis" ,
"P. capillosus | L. asaccharolyticus" ,
"O. valericigenes 1"	,
"D. freteri 1"
 )

colnames(top.coef2)[2] <- "Coefficient"
top.coef2 %>% ggplot(aes(x = reorder(Taxa, Coefficient), y =Coefficient)) + geom_bar(stat = "identity") + coord_flip() + theme_bw(base_size = 14) + xlab("Top 10 taxa coefficients")
#ggsave("../Figures/Figure 5c Btheta.pdf", height = 5)
```


