# After reviews redoing figure 2 to compare to water cage group, not to baseline day
# Mariia Taguer
# Feb 14 2024

# Load in libraries
```{r}
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(vegan)))
suppressWarnings(suppressMessages(library(RColorBrewer)))
suppressWarnings(suppressMessages(library(rstatix)))
suppressWarnings(suppressMessages(library(tidygraph)))
suppressWarnings(suppressMessages(library(ggraph)))
suppressWarnings(suppressMessages(library(pheatmap)))
suppressWarnings(suppressMessages(library(umap)))
theme_set(theme_bw(base_size = 16))
source("Functions.R")
```

# Load image count data that was generated with "Image_Diversity_Prep.R"
```{r}
# set Analysis as your working directory
Counts.df <- read.csv("../data/Counts_df.csv") %>% select(-1) # removes rownumbers
# turn treatment into factor for ordering and change their order
Counts.df$Treatment <- factor(Counts.df$Treatment, levels=c('Water', 'Ampicillin', 'Vancomycin')) 
# Set colour palette
colours <- c("#335780", "#96BBE4", "#D5490C",
          "#F1BA69",  "#03663F", "#71D68E")
```

# 2A Absolute counts
```{r}
# statistical analysis
Counts.stats <- Counts.df %>%
  ungroup() %>%
  select(Mouse, Tissue, Section, FoV, Total, Treatment, Day) %>%
  distinct() %>%
  group_by(Tissue, Day) %>%
  rstatix::wilcox_test(Total ~ Treatment) %>%
  add_xy_position(x = "Treatment")

# plot
Counts.df %>%
  ungroup() %>%
  select(Mouse, Tissue, Section, FoV, Total, Treatment, Day) %>%
  distinct() %>%
  ggplot(aes(x = Treatment, y = Total, colour = interaction(Tissue,Treatment, sep = ":"))) +
  geom_violin(scale = "width", draw_quantiles = 0.5) + 
  geom_jitter(width = 0.2, alpha = 0.3)  + 
  facet_grid(Tissue~Day) +
  stat_pvalue_manual(Counts.stats, hide.ns = TRUE, size = 6, y.position = 4.5, step.increase = 0.15,
                     step.group.by = c("Day", "Tissue")) +
  theme(text = element_text(size = 20))  +
  scale_y_log10(labels = scales::label_log(), limits = c(1, 1000000)) +  
  ylab("HiPR-FISH counts per FoV") + 
  xlab("Treatment") +
  scale_colour_manual(values=colours) + 
  scale_x_discrete(labels=c('W', 'A', 'V')) +
  theme(legend.position = "none")
  
#ggsave("../Figures/RevisedFig2a.pdf", height = 6)
#
```


# 2B species counts
```{r}
# statistical analysis
SpeciesCounts.stats <- Counts.df %>%
  select(Tissue, Mouse, Section, FoV, SpeciesCount, Treatment, Day) %>%
  distinct() %>% 
  group_by(Tissue, Day) %>%
  rstatix::pairwise_wilcox_test(SpeciesCount ~ Treatment) %>%
  add_xy_position(x = "Treatment")

# plot
Counts.df %>%
  select(Tissue, Mouse, Section, FoV, SpeciesCount, Treatment, Day) %>%
  distinct() %>%
  ggplot(aes(x = Treatment, y = SpeciesCount, colour = interaction(Tissue,Treatment, sep = ":"))) + 
  geom_violin(scale = "width", draw_quantiles = 0.5) + geom_jitter(width = 0.2, alpha = 0.2)  + 
  facet_grid(Tissue ~ Day) +
  xlab("Day") +
  theme(text = element_text(size = 20)) +
  stat_pvalue_manual(SpeciesCounts.stats, hide.ns = TRUE, size = 6, bracket.nudge.y = 25) +
  theme(text = element_text(size = 20))  +
  ylim(0,90) +
  scale_colour_manual(values=colours) +
  labs(color = "Tissue and Treatment") + 
  scale_x_discrete(labels=c('W', 'A', 'V')) +
  theme(legend.position = "none") +
  ylab("Species Count per FoV")

#ggsave("../Figures/RevisedFig2b.pdf", height = 6)
```

# 2C Shannon
```{r}
# make df wide
Counts.df$Sample <- paste(Counts.df$Treatment, Counts.df$Day, Counts.df$Tissue, Counts.df$Mouse,
                          Counts.df$Section, Counts.df$FoV, sep = "_") 

Counts.wide <- Counts.df %>%
  select(Sample, ASV_Cluster_ID, Count) %>%
  pivot_wider(names_from = ASV_Cluster_ID, values_from = Count) %>% 
  column_to_rownames("Sample")

# replace NA with 0
Counts.wide[is.na(Counts.wide)] <- 0

# Calculate Shannon diveristy
Shannon <- diversity(Counts.wide) 
Shannon <- Shannon %>% as.data.frame()
colnames(Shannon) <- "Shannon"
Shannon <- Shannon %>% rownames_to_column("Sample")

# join shannon with metadata
Alpha.Div <- Counts.df %>%
  pivot_wider(names_from = ASV_Cluster_ID, values_from = Count) %>%
  select(Tissue, Treatment, Day, Sample, Mouse) %>%
  right_join(Shannon, by = "Sample")

# statistical analysis
Shannon.stats <- Alpha.Div %>%
  ungroup() %>%
  select(Mouse, Tissue,  Shannon, Treatment, Day) %>%
  distinct() %>% 
  group_by(Tissue, Day) %>%
  rstatix::wilcox_test(Shannon ~ Treatment) %>%
  add_xy_position(x = "Treatment")

# plot FIGURE 2C
Alpha.Div %>%
  ungroup() %>%
  distinct() %>% 
  ggplot(aes(x = Treatment, y = Shannon, colour = interaction(Tissue,Treatment, sep = ":"))) + 
  geom_violin(scale = "width", draw_quantiles = 0.5) + geom_jitter(width = 0.2, alpha = 0.3)  + 
  facet_grid(Tissue~Day) +
  xlab("Day") +
  ylab("Shannon's Index per FoV") +
  theme(text = element_text(size = 20)) +
  stat_pvalue_manual(Shannon.stats, hide.ns = TRUE, size = 6, step.increase = 0.04) +
  theme(text = element_text(size = 20))  +
  ylim(c(0,4.5)) +
  scale_colour_manual(values=colours) +
  labs(color = "Tissue and Treatment") + 
  scale_x_discrete(labels=c('W', 'A', 'V')) +
  theme(legend.position = "none") 

#ggsave("../Figures/RevisedFig2c.pdf", height = 6)
```

# 2D Add in Simpsons
```{r}
# calculate Simpsons diversity
Simpson <- diversity(Counts.wide, index = "simpson") 
Simpson <- Simpson %>% as.data.frame()
colnames(Simpson) <- "Simpson"
Simpson <- Simpson %>% rownames_to_column("Sample")

# join with metadata
Simpson.Div <- Counts.df %>%
  pivot_wider(names_from = ASV_Cluster_ID, values_from = Count) %>%
  select(Tissue, Treatment, Day, Sample, Mouse) %>%
  right_join(Simpson, by = "Sample")

# statistical analysis
Simpson.stats <- Simpson.Div %>%
  ungroup() %>%
  select(Mouse, Tissue, Simpson, Treatment, Day) %>%
  distinct() %>% 
  group_by(Tissue, Day) %>%
  rstatix::wilcox_test(Simpson ~ Treatment) %>%
  add_xy_position(x = "Treatment")

# Compare between tissues
Simpson.stats2 <- Simpson.Div %>%
  select(Tissue, Mouse,  Simpson, Treatment, Day) %>%
  distinct() %>% 
  group_by(Day, Treatment) %>% 
  rstatix::pairwise_wilcox_test(Simpson ~ Tissue) %>%
  add_xy_position(x = "Day")


# plot FIGURE 2d
Simpson.Div %>%
  ungroup() %>%
  distinct() %>% 
  ggplot(aes(x = Treatment, y = Simpson, colour = interaction(Tissue,Treatment, sep = ":"))) + 
  geom_violin(scale = "width", draw_quantiles = 0.5) + geom_jitter(width = 0.2, alpha = 0.3)  + 
  facet_grid(Tissue~Day) +
  ylab("Simpson's Index per FoV") +
  xlab("Day") +
  theme(text = element_text(size = 20)) +
  stat_pvalue_manual(Simpson.stats, hide.ns = TRUE, size = 6, step.group.by = c("Day", "Tissue"),
                     step.increase = 0.15, y.position = 1.2) +
  theme(text = element_text(size = 20))  +
  ylim(c(0,1.8)) +
  scale_colour_manual(values=colours) +
  labs(color = "Tissue and Treatment") + 
  scale_x_discrete(labels=c('W', 'A', 'V')) +
  theme(legend.position = "none") 
#ggsave("../RevisedFig2Simpsons.pdf", height = 6)
```

# Bray curtis prep
```{r}
# make a df that is observation (sample) by variable 
Counts.df$Sample <- paste(Counts.df$Treatment, Counts.df$Day, Counts.df$Tissue, Counts.df$Mouse,
                          Counts.df$Section, Counts.df$FoV, sep = "_") 
Counts.wide <- Counts.df %>%
  select(Sample, ASV_Cluster_ID, Count) %>% 
  pivot_wider(Sample, names_from = ASV_Cluster_ID, values_from = Count) 

# turn sample to rowname, replace na with 0
Counts.wide <- Counts.wide %>% column_to_rownames("Sample")
Counts.wide <- replace(Counts.wide,is.na(Counts.wide),0)
# calculate bray curtis
All.BC <- vegdist(Counts.wide, "bray")
All.BC.mat <- as.matrix(All.BC) 
All.BC.mat[lower.tri(All.BC.mat)] <- NA #get just the upper triangle
All.BC.df <- All.BC.mat %>%
  as.data.frame() %>%
  rownames_to_column("Var1")  %>%
  pivot_longer(-Var1, names_to = "Var2", values_to = "BC") 

# join it with metadata
All.BC.df.md <- left_join(All.BC.df, 
                          select(Counts.df, c(Mouse, Tissue, Section, FoV, Treatment, Day, Sample)),
                          by = c("Var1" = "Sample")) %>%
  filter(Var1 != Var2)  %>% # removes self comparisons
  distinct()

All.BC.df.md <- left_join(All.BC.df.md, 
                          select(Counts.df, c(Mouse, Tissue, Section, FoV, Treatment, Day, Sample)), 
                          by = c("Var2" = "Sample")) %>%
  filter(Var1 != Var2)  %>% # removes self comparisons
  distinct()

# statistical analysis
BC.counts.Wilcox <- All.BC.df.md %>%
  filter(Day.x == -8) %>%
  filter(Tissue.x == Tissue.y) %>%
  filter(Treatment.x == Treatment.y) %>%
  group_by(Treatment.x, Tissue.x) %>%
  filter(!is.na(BC)) %>%
  rstatix::pairwise_wilcox_test(BC ~ Day.y, ref.group = "-8")

BC.counts.Wilcox <- BC.counts.Wilcox %>% add_xy_position(x = "Day.y")
```

# Figure 2E Beta diver
```{r}
# statistical analysis
BC.counts.Wilcox <-All.BC.df.md %>%
  filter(Treatment.x == "Water") %>%
  filter(Tissue.x == Tissue.y) %>%
  filter(Day.x == Day.y) %>%
  distinct() %>% 
  group_by(Day.y, Tissue.x) %>%
  filter(!is.na(BC))  %>% rstatix::pairwise_wilcox_test(BC ~ Treatment.y) %>% 
  add_xy_position(x = "Treatment.y")

# plot
All.BC.df.md %>%
  filter(Treatment.x == "Water") %>%
  filter(Tissue.x == Tissue.y) %>%
  filter(Day.x == Day.y) %>%
  distinct() %>% 
  ggplot(aes(x= Treatment.y, y=BC, colour = interaction(Tissue.y, Treatment.y))) +
  geom_violin(scale = "width", draw_quantiles = 0.5) + 
  geom_point(position=position_jitterdodge(2), alpha = 0.05)  +  
  ylab("Bray-Curtis dissimilarity") +
  facet_grid(Tissue.x ~ Day.y) +
  xlab(" ") +
  theme(text = element_text(size = 20)) +
  stat_pvalue_manual(BC.counts.Wilcox, hide.ns = TRUE, size = 6, step.increase = 0.15,
                     step.group.by = c("Day.y", "Tissue.x"), y.position = 1.2) +
  ylim(0,1.8) +
  scale_colour_manual(values=colours) + 
  scale_x_discrete(labels=c('W', 'A', 'V')) +
  theme(legend.position = "none") 

#ggsave("../Figures/RevisedFig2eBC_towater.pdf", height = 6)
```

# Figure 2F
```{r}
# statistical analysis
BC.counts.Tissue <- All.BC.df.md %>%
  filter(Treatment.x == "Water") %>%
  filter(Tissue.x == Tissue.y) %>%
  filter(Day.x == Day.y) %>%
  distinct() %>%
  group_by(Treatment.y, Day.y) %>%
  filter(!is.na(BC))%>%
  rstatix::pairwise_wilcox_test(BC ~ Tissue.x) %>%
  add_xy_position(x = "Treatment.y")

# plot
All.BC.df.md %>%
  filter(Treatment.x == "Water") %>% 
  filter(Tissue.x == Tissue.y) %>% 
  filter(Day.x == Day.y) %>%
  distinct() %>% 
  ggplot(aes(x= Treatment.y, y=BC, colour = interaction(Tissue.x, Treatment.y))) +
  geom_violin(scale = "width", draw_quantiles = 0.5) + 
  geom_point(position=position_jitterdodge(2), alpha = 0.05)  +  
  ylab("Bray-Curtis dissimilarity") +
  facet_grid( ~ Day.y) +
  xlab(" ") +
  theme(text = element_text(size = 20)) +
  stat_pvalue_manual(BC.counts.Tissue, hide.ns = TRUE, size = 6, y.position = 1.1) +
  ylim(0,1.3) +
  scale_colour_manual(values=colours) + 
  scale_x_discrete(labels=c('W', 'A', 'V')) +
  theme(legend.position = "none") 

#ggsave("../Figures/RevisedFig2eBCTissue_byWater.pdf", height = 4)
```



